
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DRIVER_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

groq.api.key=${GROQ_API_KEY}
groq.api.model=llama-3.3-70b-versatile
groq.api.translation-model=llama-3.1-8b-instant
groq.api.url=https://api.groq.com/openai/v1/chat/completions


app.cors.allowed-origins=${VITE_API_BASE_URL}

logging.level.com.example.voice.commanding=DEBUG
logging.level.org.springframework.web=INFO
