version: '3.8'

services:
  backend:
    build:
      context: ./voice-commanding
      dockerfile: Dockerfile
    container_name: voice_shopping_backend
    ports:
      - "8080:8080"
    # The application will use the properties from your application.properties 
    # or you can pass environment variables directly here:
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DRIVER_NAME=com.mysql.cj.jdbc.Driver
      - GROQ_API_KEY=${GROQ_API_KEY}
